#XByX@TroJanzHEX
importXasyncio
importXos
importXshutil


asyncXdefXnormalglitch_1(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"normalglitch_1.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-o",Xedit_img_loc,Xdownload_location,X"1"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("normalglitch_1-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXnormalglitch_2(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"normalglitch_2.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-o",Xedit_img_loc,Xdownload_location,X"2"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("normalglitch_2-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXnormalglitch_3(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"normalglitch_3.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-o",Xedit_img_loc,Xdownload_location,X"3"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("normalglitch_3-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXnormalglitch_4(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"normalglitch_4.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-o",Xedit_img_loc,Xdownload_location,X"4"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("normalglitch_4-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXnormalglitch_5(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"normalglitch_5.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-o",Xedit_img_loc,Xdownload_location,X"5"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("normalglitch_5-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXscanlineglitch_1(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"scanlineglitch_1.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-s",X"-o",Xedit_img_loc,Xdownload_location,X"1"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("scanlineglitch_1-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXscanlineglitch_2(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"scanlineglitch_2.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-s",X"-o",Xedit_img_loc,Xdownload_location,X"2"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("scanlineglitch_2-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXscanlineglitch_3(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"scanlineglitch_3.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-s",X"-o",Xedit_img_loc,Xdownload_location,X"3"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("scanlineglitch_3-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXscanlineglitch_4(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"scanlineglitch_4.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-s",X"-o",Xedit_img_loc,Xdownload_location,X"4"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("scanlineglitch_4-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXscanlineglitch_5(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"scanlineglitch_5.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXcdX=X["glitch_this",X"-c",X"-s",X"-o",Xedit_img_loc,Xdownload_location,X"5"]
XXXXXXXXXXXXprocessX=XawaitXasyncio.create_subprocess_exec(
XXXXXXXXXXXXXXXX*cd,Xstdout=asyncio.subprocess.PIPE,Xstderr=asyncio.subprocess.PIPE
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXprocess.communicate()
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("scanlineglitch_5-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn
