#By@TroJanzHE
importasyncio
importos
importshutil


asyncdefnormalglitch_1(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"normalglitch_1.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-o",edit_img_loc,download_location,"1"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("normalglitch_1-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefnormalglitch_2(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"normalglitch_2.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-o",edit_img_loc,download_location,"2"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("normalglitch_2-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefnormalglitch_3(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"normalglitch_3.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-o",edit_img_loc,download_location,"3"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("normalglitch_3-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefnormalglitch_4(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"normalglitch_4.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-o",edit_img_loc,download_location,"4"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("normalglitch_4-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefnormalglitch_5(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"normalglitch_5.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-o",edit_img_loc,download_location,"5"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("normalglitch_5-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefscanlineglitch_1(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"scanlineglitch_1.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-s","-o",edit_img_loc,download_location,"1"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("scanlineglitch_1-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefscanlineglitch_2(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"scanlineglitch_2.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-s","-o",edit_img_loc,download_location,"2"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("scanlineglitch_2-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefscanlineglitch_3(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"scanlineglitch_3.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-s","-o",edit_img_loc,download_location,"3"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("scanlineglitch_3-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefscanlineglitch_4(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"scanlineglitch_4.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-s","-o",edit_img_loc,download_location,"4"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("scanlineglitch_4-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefscanlineglitch_5(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"scanlineglitch_5.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
cd=["glitch_this","-c","-s","-o",edit_img_loc,download_location,"5"]
process=awaitasyncio.create_subprocess_exec(
*cd,stdout=asyncio.subprocess.PIPE,stderr=asyncio.subprocess.PIPE
)
awaitprocess.communicate()
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("scanlineglitch_5-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return
