#XByX@TroJanzHEX
importXos
importXshutil

fromXPILXimportXImage,XImageOps


asyncXdefXblack_border(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"imaged-black-border.png"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXimgX=XImage.open(a)
XXXXXXXXXXXXimg_with_borderX=XImageOps.expand(img,Xborder=100,Xfill="black")
XXXXXXXXXXXXimg_with_border.save(edit_img_loc)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("black_border-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXgreen_border(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"imaged-green-border.png"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXimgX=XImage.open(a)
XXXXXXXXXXXXimg_with_borderX=XImageOps.expand(img,Xborder=100,Xfill="green")
XXXXXXXXXXXXimg_with_border.save(edit_img_loc)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("green_border-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXblue_border(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"imaged-blue-border.png"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXimgX=XImage.open(a)
XXXXXXXXXXXXimg_with_borderX=XImageOps.expand(img,Xborder=100,Xfill="blue")
XXXXXXXXXXXXimg_with_border.save(edit_img_loc)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("blue_border-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXred_border(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"imaged-red-border.png"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXimgX=XImage.open(a)
XXXXXXXXXXXXimg_with_borderX=XImageOps.expand(img,Xborder=100,Xfill="red")
XXXXXXXXXXXXimg_with_border.save(edit_img_loc)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("red_border-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn
