#By@TroJanzHE
importos
importshutil

importcv2
importnumpyasnp
fromPILimportImage,ImageDraw,ImageEnhance


asyncdefcircle_with_bg(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"circle.png"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
img=Image.open(a).convert("RGB")
npImage=np.array(img)
h,w=img.size
alpha=Image.new("L",img.size,0)
draw=ImageDraw.Draw(alpha)
draw.pieslice([0,0,h,w],0,360,fill=255)
npAlpha=np.array(alpha)
npImage=np.dstack((npImage,npAlpha))
Image.fromarray(npImage).save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("circle_with_bg-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefcircle_without_bg(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"circle.png"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
img=Image.open(a).convert("RGB")
npImage=np.array(img)
h,w=img.size
alpha=Image.new("L",img.size,0)
draw=ImageDraw.Draw(alpha)
draw.pieslice([0,0,h,w],0,360,fill=255)
npAlpha=np.array(alpha)
npImage=np.dstack((npImage,npAlpha))
Image.fromarray(npImage).save(edit_img_loc)
awaitmessage.reply_chat_action("upload_document")
awaitmessage.reply_to_message.reply_document(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("circle_without_bg-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefsticker(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"sticker.webp"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
os.rename(a,edit_img_loc)
awaitmessage.reply_to_message.reply_sticker(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("sticker-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


defadd_corners(im,rad):
circle=Image.new("L",(rad*2,rad*2),0)
draw=ImageDraw.Draw(circle)
draw.ellipse((0,0,rad*2,rad*2),fill=255)
alpha=Image.new("L",im.size,255)
w,h=im.size
alpha.paste(circle.crop((0,0,rad,rad)),(0,0))
alpha.paste(circle.crop((0,rad,rad,rad*2)),(0,h-rad))
alpha.paste(circle.crop((rad,0,rad*2,rad)),(w-rad,0))
alpha.paste(circle.crop((rad,rad,rad*2,rad*2)),(w-rad,h-rad))
im.putalpha(alpha)
returnim


asyncdefedge_curved(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"edge_curved.webp"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
im=Image.open(a)
im=add_corners(im,100)
im.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_sticker(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("edge_curved-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefcontrast(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"contrast.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
image=Image.open(a)
contrast=ImageEnhance.Contrast(image)
contrast.enhance(1.5).save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("contrast-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


defsepia(img):
width,height=img.size
new_img=img.copy()
forxinrange(width):
foryinrange(height):
red,green,blue=img.getpixel((x,y))
new_val=0.3*red+0.59*green+0.11*blue
new_red=int(new_val*2)
ifnew_red>255:
new_red=255
new_green=int(new_val*1.5)
ifnew_green>255:
new_green=255
new_blue=int(new_val)
ifnew_blue>255:
new_blue=255

new_img.putpixel((x,y),(new_red,new_green,new_blue))

returnnew_img


asyncdefsepia_mode(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"sepia.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
image=Image.open(a)
new_img=sepia(image)
new_img.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("sepia_mode-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


defdodgeV2(x,y):
returncv2.divide(x,255-y,scale=256)


asyncdefpencil(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"pencil.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
img=cv2.imread(a)
img_gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img_invert=cv2.bitwise_not(img_gray)
img_smoothing=cv2.GaussianBlur(img_invert,(21,21),sigma=0,sigmaY=0)
final_img=dodgeV2(img_gray,img_smoothing)
cv2.imwrite(edit_img_loc,final_img)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("pencil-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


defcolor_quantization(img,k):
data=np.float32(img).reshape((-1,3))
criteria=(cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MA_ITER,20,1.0)
_,label,center=cv2.kmeans(
data,k,None,criteria,10,cv2.KMEANS_RANDOM_CENTERS
)
center=np.uint8(center)
result=center[label.flatten()]
result=result.reshape(img.shape)
returnresult


asyncdefcartoon(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"kang.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
img=cv2.imread(a)
edges=cv2.Canny(img,100,200)
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges=cv2.adaptiveThreshold(
gray,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,9,5
)
color=cv2.bilateralFilter(img,d=9,sigmaColor=200,sigmaSpace=200)

cv2.bitwise_and(color,color,mask=edges)
img_1=color_quantization(img,7)
cv2.imwrite(edit_img_loc,img_1)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("cartoon-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return
