#By@TroJanzHE
importio
importos
importshutil

importcv2
importnumpyasnp
importrequests
fromPILimportImage,ImageDraw,ImageOps

fromIneruki.configimportget_str_key

RemoveBG_API=get_str_key("REM_BG_API_KEY",required=False)


asyncdefrotate_90(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"rotate_90.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
src=cv2.imread(a)
image=cv2.rotate(src,cv2.cv2.ROTATE_90_CLOCKWISE)
cv2.imwrite(edit_img_loc,image)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("rotate_90-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefrotate_180(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"rotate_180.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
src=cv2.imread(a)
image=cv2.rotate(src,cv2.ROTATE_180)
cv2.imwrite(edit_img_loc,image)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("rotate_180-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefrotate_270(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"rotate_270.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
src=cv2.imread(a)
image=cv2.rotate(src,cv2.ROTATE_90_COUNTERCLOCKWISE)
cv2.imwrite(edit_img_loc,image)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("rotate_270-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


defresize_photo(photo:str,userid:str)->io.BytesIO:
image=Image.open(photo)
maxsize=512
scale=maxsize/max(image.width,image.height)
new_size=(int(image.width*scale),int(image.height*scale))
image=image.resize(new_size,Image.LANCZOS)
resized_photo=io.BytesIO()
resized_photo.name="./DOWNLOADS"+"/"+userid+"resized.png"
image.save(resized_photo,"PNG")
returnresized_photo


asyncdefround_sticker(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"rounded.webp"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
resized=resize_photo(a,userid)
img=Image.open(resized).convert("RGB")
npImage=np.array(img)
h,w=img.size
alpha=Image.new("L",img.size,0)
draw=ImageDraw.Draw(alpha)
draw.pieslice([0,0,h,w],0,360,fill=255)
npAlpha=np.array(alpha)
npImage=np.dstack((npImage,npAlpha))
Image.fromarray(npImage).save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_sticker(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("round_sticker-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefinverted(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"inverted.png"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
image=Image.open(a)
inverted_image=ImageOps.invert(image)
inverted_image.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("inverted-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefremovebg_plain(client,message):
try:
ifnot(RemoveBG_API==""):
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"nobgplain.png"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")

response=requests.post(
"https://api.remove.bg/v1.0/removebg",
files={"image_file":open(download_location,"rb")},
data={"size":"auto"},
headers={"-Api-Key":RemoveBG_API},
)
ifresponse.status_code==200:
withopen(f"{edit_img_loc}","wb")asout:
out.write(response.content)
else:
awaitmessage.reply_to_message.reply_text(
"Checkifyourapiiscorrect",quote=True
)
return

awaitmessage.reply_chat_action("upload_document")
awaitmessage.reply_to_message.reply_document(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
else:
awaitmessage.reply_to_message.reply_text(
"Gettheapifromhttps://www.remove.bg/b/background-removal-apiandaddinConfigVar",
quote=True,
disable_web_page_preview=True,
)
exceptExceptionase:
print("removebg_plain-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefremovebg_white(client,message):
try:
ifnot(RemoveBG_API==""):
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"nobgwhite.png"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")

response=requests.post(
"https://api.remove.bg/v1.0/removebg",
files={"image_file":open(download_location,"rb")},
data={"size":"auto"},
headers={"-Api-Key":Config.RemoveBG_API},
)
ifresponse.status_code==200:
withopen(f"{edit_img_loc}","wb")asout:
out.write(response.content)
else:
awaitmessage.reply_to_message.reply_text(
"Checkifyourapiiscorrect",quote=True
)
return

awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
else:
awaitmessage.reply_to_message.reply_text(
"Gettheapifromhttps://www.remove.bg/b/background-removal-apiandaddinConfigVar",
quote=True,
disable_web_page_preview=True,
)
exceptExceptionase:
print("removebg_white-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefremovebg_sticker(client,message):
try:
ifnot(RemoveBG_API==""):
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"nobgsticker.webp"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")

response=requests.post(
"https://api.remove.bg/v1.0/removebg",
files={"image_file":open(download_location,"rb")},
data={"size":"auto"},
headers={"-Api-Key":RemoveBG_API},
)
ifresponse.status_code==200:
withopen(f"{edit_img_loc}","wb")asout:
out.write(response.content)
else:
awaitmessage.reply_to_message.reply_text(
"Checkifyourapiiscorrect",quote=True
)
return

awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_sticker(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
else:
awaitmessage.reply_to_message.reply_text(
"Gettheapifromhttps://www.remove.bg/b/background-removal-apiandaddinConfigVar",
quote=True,
disable_web_page_preview=True,
)
exceptExceptionase:
print("removebg_sticker-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return
