#By@TroJanzHE
importos
importshutil

fromPILimportImage,ImageOps


asyncdefblack_border(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"imaged-black-border.png"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
img=Image.open(a)
img_with_border=ImageOps.expand(img,border=100,fill="black")
img_with_border.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("black_border-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefgreen_border(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"imaged-green-border.png"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
img=Image.open(a)
img_with_border=ImageOps.expand(img,border=100,fill="green")
img_with_border.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("green_border-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefblue_border(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"imaged-blue-border.png"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
img=Image.open(a)
img_with_border=ImageOps.expand(img,border=100,fill="blue")
img_with_border.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("blue_border-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefred_border(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"imaged-red-border.png"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
img=Image.open(a)
img_with_border=ImageOps.expand(img,border=100,fill="red")
img_with_border.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("red_border-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return
