#By@TroJanzHE
importos
importshutil

importcv2
fromPILimportImage,ImageEnhance,ImageFilter


asyncdefbright(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"brightness.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
image=Image.open(a)
brightness=ImageEnhance.Brightness(image)
brightness.enhance(1.5).save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("bright-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefmix(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"mix.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
image=Image.open(a)
red,green,blue=image.split()
new_image=Image.merge("RGB",(green,red,blue))
new_image.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("mix-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefblack_white(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"black_white.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
image_file=cv2.imread(a)
grayImage=cv2.cvtColor(image_file,cv2.COLOR_BGR2GRAY)
cv2.imwrite(edit_img_loc,grayImage)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("black_white-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefnormal_blur(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"BlurImage.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
OriImage=Image.open(a)
blurImage=OriImage.filter(ImageFilter.BLUR)
blurImage.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("normal_blur-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefg_blur(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"gaussian_blur.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
im1=Image.open(a)
im2=im1.filter(ImageFilter.GaussianBlur(radius=5))
im2.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("g_blur-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return


asyncdefbox_blur(client,message):
try:
userid=str(message.chat.id)
ifnotos.path.isdir(f"./DOWNLOADS/{userid}"):
os.makedirs(f"./DOWNLOADS/{userid}")
download_location="./DOWNLOADS"+"/"+userid+"/"+userid+".jpg"
edit_img_loc="./DOWNLOADS"+"/"+userid+"/"+"box_blur.jpg"
ifnotmessage.reply_to_message.empty:
msg=awaitmessage.reply_to_message.reply_text(
"Downloadingimage",quote=True
)
a=awaitclient.download_media(
message=message.reply_to_message,file_name=download_location
)
awaitmsg.edit("ProcessingImage...")
im1=Image.open(a)
im2=im1.filter(ImageFilter.BoxBlur(0))
im2.save(edit_img_loc)
awaitmessage.reply_chat_action("upload_photo")
awaitmessage.reply_to_message.reply_photo(edit_img_loc,quote=True)
awaitmsg.delete()
else:
awaitmessage.reply_text("Whydidyoudeletethat??")
try:
shutil.rmtree(f"./DOWNLOADS/{userid}")
exceptException:
pass
exceptExceptionase:
print("box_blur-error-"+str(e))
if"USER_IS_BLOCKED"instr(e):
return
else:
try:
awaitmessage.reply_to_message.reply_text(
"Somethingwentwrong!",quote=True
)
exceptException:
return
