#XByX@TroJanzHEX
importXos
importXshutil

importXcv2
fromXPILXimportXImage,XImageEnhance,XImageFilter


asyncXdefXbright(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"brightness.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXimageX=XImage.open(a)
XXXXXXXXXXXXbrightnessX=XImageEnhance.Brightness(image)
XXXXXXXXXXXXbrightness.enhance(1.5).save(edit_img_loc)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("bright-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXmix(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"mix.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXimageX=XImage.open(a)
XXXXXXXXXXXXred,Xgreen,XblueX=Ximage.split()
XXXXXXXXXXXXnew_imageX=XImage.merge("RGB",X(green,Xred,Xblue))
XXXXXXXXXXXXnew_image.save(edit_img_loc)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("mix-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXblack_white(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"black_white.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXimage_fileX=Xcv2.imread(a)
XXXXXXXXXXXXgrayImageX=Xcv2.cvtColor(image_file,Xcv2.COLOR_BGR2GRAY)
XXXXXXXXXXXXcv2.imwrite(edit_img_loc,XgrayImage)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("black_white-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXnormal_blur(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"BlurImage.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXOriImageX=XImage.open(a)
XXXXXXXXXXXXblurImageX=XOriImage.filter(ImageFilter.BLUR)
XXXXXXXXXXXXblurImage.save(edit_img_loc)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("normal_blur-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXg_blur(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"gaussian_blur.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXim1X=XImage.open(a)
XXXXXXXXXXXXim2X=Xim1.filter(ImageFilter.GaussianBlur(radius=5))
XXXXXXXXXXXXim2.save(edit_img_loc)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("g_blur-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn


asyncXdefXbox_blur(client,Xmessage):
XXXXtry:
XXXXXXXXuseridX=Xstr(message.chat.id)
XXXXXXXXifXnotXos.path.isdir(f"./DOWNLOADS/{userid}"):
XXXXXXXXXXXXos.makedirs(f"./DOWNLOADS/{userid}")
XXXXXXXXdownload_locationX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+XuseridX+X".jpg"
XXXXXXXXedit_img_locX=X"./DOWNLOADS"X+X"/"X+XuseridX+X"/"X+X"box_blur.jpg"
XXXXXXXXifXnotXmessage.reply_to_message.empty:
XXXXXXXXXXXXmsgX=XawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXX"DownloadingXimage",Xquote=True
XXXXXXXXXXXX)
XXXXXXXXXXXXaX=XawaitXclient.download_media(
XXXXXXXXXXXXXXXXmessage=message.reply_to_message,Xfile_name=download_location
XXXXXXXXXXXX)
XXXXXXXXXXXXawaitXmsg.edit("ProcessingXImage...")
XXXXXXXXXXXXim1X=XImage.open(a)
XXXXXXXXXXXXim2X=Xim1.filter(ImageFilter.BoxBlur(0))
XXXXXXXXXXXXim2.save(edit_img_loc)
XXXXXXXXXXXXawaitXmessage.reply_chat_action("upload_photo")
XXXXXXXXXXXXawaitXmessage.reply_to_message.reply_photo(edit_img_loc,Xquote=True)
XXXXXXXXXXXXawaitXmsg.delete()
XXXXXXXXelse:
XXXXXXXXXXXXawaitXmessage.reply_text("WhyXdidXyouXdeleteXthat??")
XXXXXXXXtry:
XXXXXXXXXXXXshutil.rmtree(f"./DOWNLOADS/{userid}")
XXXXXXXXexceptXException:
XXXXXXXXXXXXpass
XXXXexceptXExceptionXasXe:
XXXXXXXXprint("box_blur-errorX-X"X+Xstr(e))
XXXXXXXXifX"USER_IS_BLOCKED"XinXstr(e):
XXXXXXXXXXXXreturn
XXXXXXXXelse:
XXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXawaitXmessage.reply_to_message.reply_text(
XXXXXXXXXXXXXXXXXXXX"SomethingXwentXwrong!",Xquote=True
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXexceptXException:
XXXXXXXXXXXXXXXXreturn
