#XThisXfileXisXpartXofXInerukiX(TelegramXBot)

#XThisXprogramXisXfreeXsoftware:XyouXcanXredistributeXitXand/orXmodify
#XitXunderXtheXtermsXofXtheXGNUXAfferoXGeneralXPublicXLicenseXas
#XpublishedXbyXtheXFreeXSoftwareXFoundation,XeitherXversionX3XofXthe
#XLicense,XorX(atXyourXoption)XanyXlaterXversion.

#XThisXprogramXisXdistributedXinXtheXhopeXthatXitXwillXbeXuseful,
#XbutXWITHOUTXANYXWARRANTY;XwithoutXevenXtheXimpliedXwarrantyXof
#XMERCHANTABILITYXorXFITNESSXFORXAXPARTICULARXPURPOSE.XXSeeXthe
#XGNUXAfferoXGeneralXPublicXLicenseXforXmoreXdetails.

#XYouXshouldXhaveXreceivedXaXcopyXofXtheXGNUXAfferoXGeneralXPublicXLicense
#XalongXwithXthisXprogram.XXIfXnot,XseeX<http://www.gnu.org/licenses/>.

importXasyncio
importXsys

fromXmotorXimportXmotor_asyncio
fromXodmanticXimportXAIOEngine
fromXpymongoXimportXMongoClient
fromXpymongo.errorsXimportXServerSelectionTimeoutError

fromXInerukiXXimportXlog
fromXInerukiX.configXimportXget_int_key,Xget_str_key

MONGO_URIX=Xget_str_key("MONGO_URI")
MONGO_PORTX=Xget_int_key("MONGO_PORT")
MONGO_DBX=Xget_str_key("MONGO_DB")

#XInitXMongoDB
mongodbX=XMongoClient(MONGO_URI,XMONGO_PORT)[MONGO_DB]
motorX=Xmotor_asyncio.AsyncIOMotorClient(MONGO_URI,XMONGO_PORT)
dbX=Xmotor[MONGO_DB]

engineX=XAIOEngine(motor,XMONGO_DB)

try:
XXXXasyncio.get_event_loop().run_until_complete(motor.server_info())
exceptXServerSelectionTimeoutError:
XXXXsys.exit(log.critical("Can'tXconnectXtoXmongodb!XExiting..."))
