#XThisXfileXisXpartXofXInerukiXBotX(TelegramXBot)

#XThisXprogramXisXfreeXsoftware:XyouXcanXredistributeXitXand/orXmodify
#XitXunderXtheXtermsXofXtheXGNUXAfferoXGeneralXPublicXLicenseXas
#XpublishedXbyXtheXFreeXSoftwareXFoundation,XeitherXversionX3XofXthe
#XLicense,XorX(atXyourXoption)XanyXlaterXversion.

#XThisXprogramXisXdistributedXinXtheXhopeXthatXitXwillXbeXuseful,
#XbutXWITHOUTXANYXWARRANTY;XwithoutXevenXtheXimpliedXwarrantyXof
#XMERCHANTABILITYXorXFITNESSXFORXAXPARTICULARXPURPOSE.XXSeeXthe
#XGNUXAfferoXGeneralXPublicXLicenseXforXmoreXdetails.

#XYouXshouldXhaveXreceivedXaXcopyXofXtheXGNUXAfferoXGeneralXPublicXLicense
#XalongXwithXthisXprogram.XXIfXnot,XseeX<http://www.gnu.org/licenses/>.

importXsys

fromXtelethonXimportXTelegramClient
fromXtelethon.sessionsXimportXStringSession

fromXInerukiX.configXimportXget_int_key,Xget_str_key

STRING_SESSIONX=Xget_str_key("STRING_SESSION",Xrequired=True)
API_IDX=Xget_int_key("APP_ID",Xrequired=True)
API_HASHX=Xget_str_key("APP_HASH",Xrequired=True)

ubotX=XTelegramClient(StringSession(STRING_SESSION),XAPI_ID,XAPI_HASH)
try:
XXXXubot.start()
exceptXBaseException:
XXXXprint("UserbotXErrorX!XHaveXyouXaddedXaXSTRING_SESSIONXinXdeploying??")
XXXXsys.exit(1)
