#ThisfileispartofInerukiBot(TelegramBot)

#Thisprogramisfreesoftware:youcanredistributeitand/ormodify
#itunderthetermsoftheGNUAfferoGeneralPublicLicenseas
#publishedbytheFreeSoftwareFoundation,eitherversion3ofthe
#License,or(atyouroption)anylaterversion.

#Thisprogramisdistributedinthehopethatitwillbeuseful,
#butWITHOUTANYWARRANTY;withouteventheimpliedwarrantyof
#MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.Seethe
#GNUAfferoGeneralPublicLicenseformoredetails.

#YoushouldhavereceivedacopyoftheGNUAfferoGeneralPublicLicense
#alongwiththisprogram.Ifnot,see<http://www.gnu.org/licenses/>.


defshorten(description,info="anilist.co"):
ms_g=""
iflen(description)>700:
description=description[0:500]+"..."
ms_g+=(
f"\n<b>Description</b>:<i>{description}</i><ahref='{info}'>ReadMore</a>"
)
else:
ms_g+=f"\n<b>Description</b>:<i>{description}</i>"
return(
ms_g.replace("<br>","")
.replace("</br>","")
.replace("<i>","")
.replace("</i>","")
)


deft(milliseconds:int)->str:
"""Inputstimeinmilliseconds,togetbeautifiedtime,
asstring"""
seconds,milliseconds=divmod(int(milliseconds),1000)
minutes,seconds=divmod(seconds,60)
hours,minutes=divmod(minutes,60)
days,hours=divmod(hours,24)
tmp=(
((str(days)+"Days,")ifdayselse"")
+((str(hours)+"Hours,")ifhourselse"")
+((str(minutes)+"Minutes,")ifminuteselse"")
+((str(seconds)+"Seconds,")ifsecondselse"")
+((str(milliseconds)+"ms,")ifmillisecondselse"")
)
returntmp[:-2]


airing_query="""
query($id:Int,$search:String){
Media(id:$id,type:ANIME,search:$search){
id
episodes
title{
romaji
english
native
}
siteUrl
nextAiringEpisode{
airingAt
timeUntilAiring
episode
}
}
}
"""

fav_query="""
query($id:Int){
Media(id:$id,type:ANIME){
id
title{
romaji
english
native
}
}
}
"""

anime_query="""
query($id:Int,$search:String){
Media(id:$id,type:ANIME,search:$search){
id
idMal
title{
romaji
english
native
}
description(asHtml:false)
startDate{
year
}
episodes
season
type
format
status
duration
siteUrl
studios{
nodes{
name
}
}
trailer{
id
site
thumbnail
}
averageScore
genres
bannerImage
}
}
"""
character_query="""
query($query:String){
Character(search:$query){
id
name{
first
last
full
}
siteUrl
favourites
image{
large
}
description
}
}
"""

manga_query="""
query($id:Int,$search:String){
Media(id:$id,type:MANGA,search:$search){
id
title{
romaji
english
native
}
description(asHtml:false)
startDate{
year
}
type
format
status
siteUrl
averageScore
genres
bannerImage
}
}
"""
