#XThisXfileXisXpartXofXInerukiXBotX(TelegramXBot)

#XThisXprogramXisXfreeXsoftware:XyouXcanXredistributeXitXand/orXmodify
#XitXunderXtheXtermsXofXtheXGNUXAfferoXGeneralXPublicXLicenseXas
#XpublishedXbyXtheXFreeXSoftwareXFoundation,XeitherXversionX3XofXthe
#XLicense,XorX(atXyourXoption)XanyXlaterXversion.

#XThisXprogramXisXdistributedXinXtheXhopeXthatXitXwillXbeXuseful,
#XbutXWITHOUTXANYXWARRANTY;XwithoutXevenXtheXimpliedXwarrantyXof
#XMERCHANTABILITYXorXFITNESSXFORXAXPARTICULARXPURPOSE.XXSeeXthe
#XGNUXAfferoXGeneralXPublicXLicenseXforXmoreXdetails.

#XYouXshouldXhaveXreceivedXaXcopyXofXtheXGNUXAfferoXGeneralXPublicXLicense
#XalongXwithXthisXprogram.XXIfXnot,XseeX<http://www.gnu.org/licenses/>.


defXshorten(description,Xinfo="anilist.co"):
XXXXms_gX=X""
XXXXifXlen(description)X>X700:
XXXXXXXXdescriptionX=Xdescription[0:500]X+X"..."
XXXXXXXXms_gX+=X(
XXXXXXXXXXXXf"\n<b>Description</b>:X<i>{description}</i>X<aXhref='{info}'>ReadXMore</a>"
XXXXXXXX)
XXXXelse:
XXXXXXXXms_gX+=Xf"\n<b>Description</b>:X<i>{description}</i>"
XXXXreturnX(
XXXXXXXXms_g.replace("<br>",X"")
XXXXXXXX.replace("</br>",X"")
XXXXXXXX.replace("<i>",X"")
XXXXXXXX.replace("</i>",X"")
XXXX)


defXt(milliseconds:Xint)X->Xstr:
XXXX"""InputsXtimeXinXmilliseconds,XtoXgetXbeautifiedXtime,
XXXXasXstring"""
XXXXseconds,XmillisecondsX=Xdivmod(int(milliseconds),X1000)
XXXXminutes,XsecondsX=Xdivmod(seconds,X60)
XXXXhours,XminutesX=Xdivmod(minutes,X60)
XXXXdays,XhoursX=Xdivmod(hours,X24)
XXXXtmpX=X(
XXXXXXXX((str(days)X+X"XDays,X")XifXdaysXelseX"")
XXXXXXXX+X((str(hours)X+X"XHours,X")XifXhoursXelseX"")
XXXXXXXX+X((str(minutes)X+X"XMinutes,X")XifXminutesXelseX"")
XXXXXXXX+X((str(seconds)X+X"XSeconds,X")XifXsecondsXelseX"")
XXXXXXXX+X((str(milliseconds)X+X"Xms,X")XifXmillisecondsXelseX"")
XXXX)
XXXXreturnXtmp[:-2]


airing_queryX=X"""
XXXXqueryX($id:XInt,$search:XString)X{
XXXXXXMediaX(id:X$id,Xtype:XANIME,search:X$search)X{
XXXXXXXXid
XXXXXXXXepisodes
XXXXXXXXtitleX{
XXXXXXXXXXromaji
XXXXXXXXXXenglish
XXXXXXXXXXnative
XXXXXXXX}
XXXXXXXXsiteUrl
XXXXXXXXnextAiringEpisodeX{
XXXXXXXXXXXairingAt
XXXXXXXXXXXtimeUntilAiring
XXXXXXXXXXXepisode
XXXXXXXX}
XXXXXX}
XXXX}
XXXX"""

fav_queryX=X"""
queryX($id:XInt)X{
XXXXXXMediaX(id:X$id,Xtype:XANIME)X{
XXXXXXXXid
XXXXXXXXtitleX{
XXXXXXXXXXromaji
XXXXXXXXXXenglish
XXXXXXXXXXnative
XXXXXXXX}
XXXXX}
}
"""

anime_queryX=X"""
XXXqueryX($id:XInt,$search:XString)X{
XXXXXXMediaX(id:X$id,Xtype:XANIME,search:X$search)X{
XXXXXXXXid
XXXXXXXXidMal
XXXXXXXXtitleX{
XXXXXXXXXXromaji
XXXXXXXXXXenglish
XXXXXXXXXXnative
XXXXXXXX}
XXXXXXXXdescriptionX(asHtml:Xfalse)
XXXXXXXXstartDate{
XXXXXXXXXXXXyear
XXXXXXXXXX}
XXXXXXXXXXepisodes
XXXXXXXXXXseason
XXXXXXXXXXtype
XXXXXXXXXXformat
XXXXXXXXXXstatus
XXXXXXXXXXduration
XXXXXXXXXXsiteUrl
XXXXXXXXXXstudios{
XXXXXXXXXXXXXXnodes{
XXXXXXXXXXXXXXXXXXXname
XXXXXXXXXXXXXX}
XXXXXXXXXX}
XXXXXXXXXXtrailer{
XXXXXXXXXXXXXXXid
XXXXXXXXXXXXXXXsiteX
XXXXXXXXXXXXXXXthumbnail
XXXXXXXXXX}
XXXXXXXXXXaverageScore
XXXXXXXXXXgenres
XXXXXXXXXXbannerImage
XXXXXX}
XXXX}
"""
character_queryX=X"""
XXXXqueryX($query:XString)X{
XXXXXXXXCharacterX(search:X$query)X{
XXXXXXXXXXXXXXXid
XXXXXXXXXXXXXXXnameX{
XXXXXXXXXXXXXXXXXXXXXfirst
XXXXXXXXXXXXXXXXXXXXXlast
XXXXXXXXXXXXXXXXXXXXXfull
XXXXXXXXXXXXXXX}
XXXXXXXXXXXXXXXsiteUrl
XXXXXXXXXXXXXXXfavourites
XXXXXXXXXXXXXXXimageX{
XXXXXXXXXXXXXXXXXXXXXXXXlarge
XXXXXXXXXXXXXXX}
XXXXXXXXXXXXXXXdescription
XXXXXXXX}
XXXX}
"""

manga_queryX=X"""
queryX($id:XInt,$search:XString)X{
XXXXXXMediaX(id:X$id,Xtype:XMANGA,search:X$search)X{
XXXXXXXXid
XXXXXXXXtitleX{
XXXXXXXXXXromaji
XXXXXXXXXXenglish
XXXXXXXXXXnative
XXXXXXXX}
XXXXXXXXdescriptionX(asHtml:Xfalse)
XXXXXXXXstartDate{
XXXXXXXXXXXXyear
XXXXXXXXXX}
XXXXXXXXXXtype
XXXXXXXXXXformat
XXXXXXXXXXstatus
XXXXXXXXXXsiteUrl
XXXXXXXXXXaverageScore
XXXXXXXXXXgenres
XXXXXXXXXXbannerImage
XXXXXX}
XXXX}
"""
