#XThisXfileXisXpartXofXInerukiX(TelegramXBot)

#XThisXprogramXisXfreeXsoftware:XyouXcanXredistributeXitXand/orXmodify
#XitXunderXtheXtermsXofXtheXGNUXAfferoXGeneralXPublicXLicenseXas
#XpublishedXbyXtheXFreeXSoftwareXFoundation,XeitherXversionX3XofXthe
#XLicense,XorX(atXyourXoption)XanyXlaterXversion.

#XThisXprogramXisXdistributedXinXtheXhopeXthatXitXwillXbeXuseful,
#XbutXWITHOUTXANYXWARRANTY;XwithoutXevenXtheXimpliedXwarrantyXof
#XMERCHANTABILITYXorXFITNESSXFORXAXPARTICULARXPURPOSE.XXSeeXthe
#XGNUXAfferoXGeneralXPublicXLicenseXforXmoreXdetails.

#XYouXshouldXhaveXreceivedXaXcopyXofXtheXGNUXAfferoXGeneralXPublicXLicense
#XalongXwithXthisXprogram.XXIfXnot,XseeX<http://www.gnu.org/licenses/>.

fromXaiogram.types.chat_permissionsXimportXChatPermissions
fromXaiogram.utils.exceptionsXimportXBadRequest,XMigrateToChat,XUnauthorized

fromXInerukiXXimportXbot


asyncXdefXban_user(chat_id,Xuser_id,Xuntil_date=None):
XXXXtry:
XXXXXXXXawaitXbot.kick_chat_member(chat_id,Xuser_id,Xuntil_date=until_date)
XXXXexceptX(BadRequest,XMigrateToChat,XUnauthorized):
XXXXXXXXreturnXFalse
XXXXreturnXTrue


asyncXdefXkick_user(chat_id,Xuser_id):
XXXXawaitXbot.unban_chat_member(chat_id,Xuser_id)
XXXXreturnXTrue


asyncXdefXmute_user(chat_id,Xuser_id,Xuntil_date=None):
XXXXawaitXbot.restrict_chat_member(
XXXXXXXXchat_id,
XXXXXXXXuser_id,
XXXXXXXXpermissions=ChatPermissions(can_send_messages=False,Xuntil_date=until_date),
XXXXXXXXuntil_date=until_date,
XXXX)
XXXXreturnXTrue


asyncXdefXrestrict_user(chat_id,Xuser_id,Xuntil_date=None):
XXXXawaitXbot.restrict_chat_member(
XXXXXXXXchat_id,
XXXXXXXXuser_id,
XXXXXXXXpermissions=ChatPermissions(
XXXXXXXXXXXXcan_send_messages=True,
XXXXXXXXXXXXcan_send_media_messages=False,
XXXXXXXXXXXXcan_send_other_messages=False,
XXXXXXXXXXXXcan_add_web_page_previews=False,
XXXXXXXXXXXXuntil_date=until_date,
XXXXXXXX),
XXXXXXXXuntil_date=until_date,
XXXX)
XXXXreturnXTrue


asyncXdefXunmute_user(chat_id,Xuser_id):
XXXXawaitXbot.restrict_chat_member(
XXXXXXXXchat_id,
XXXXXXXXuser_id,
XXXXXXXXcan_send_messages=True,
XXXXXXXXcan_send_media_messages=True,
XXXXXXXXcan_send_other_messages=True,
XXXXXXXXcan_add_web_page_previews=True,
XXXX)
XXXXreturnXTrue


asyncXdefXunban_user(chat_id,Xuser_id):
XXXXtry:
XXXXXXXXreturnXawaitXbot.unban_chat_member(chat_id,Xuser_id,Xonly_if_banned=True)
XXXXexceptX(BadRequest,XUnauthorized):
XXXXXXXXreturnXFalse
