#XCopyrightX(C)X2021Xerrorshivansh


#XThisXfileXisXpartXofXInerukiX(TelegramXBot)

#XThisXprogramXisXfreeXsoftware:XyouXcanXredistributeXitXand/orXmodify
#XitXunderXtheXtermsXofXtheXGNUXAfferoXGeneralXPublicXLicenseXas
#XpublishedXbyXtheXFreeXSoftwareXFoundation,XeitherXversionX3XofXthe
#XLicense,XorX(atXyourXoption)XanyXlaterXversion.

#XThisXprogramXisXdistributedXinXtheXhopeXthatXitXwillXbeXuseful,
#XbutXWITHOUTXANYXWARRANTY;XwithoutXevenXtheXimpliedXwarrantyXof
#XMERCHANTABILITYXorXFITNESSXFORXAXPARTICULARXPURPOSE.XXSeeXthe
#XGNUXAfferoXGeneralXPublicXLicenseXforXmoreXdetails.

#XYouXshouldXhaveXreceivedXaXcopyXofXtheXGNUXAfferoXGeneralXPublicXLicense
#XalongXwithXthisXprogram.XXIfXnot,XseeX<http://www.gnu.org/licenses/>.

fromXpyrogramXimportXfilters
fromXpyrogram.errorsXimportXRPCError

fromXInerukiX.function.pluginhelpersXimportXadmins_only,Xget_text
fromXInerukiX.services.pyrogramXimportXpbot


@pbot.on_message(
XXXXfilters.command("cedit")X&X~filters.editedX&X~filters.botX&X~filters.private
)
@admins_only
asyncXdefXloltime(client,Xmessage):
XXXXlolX=XawaitXmessage.reply("ProcessingXpleaseXwait")
XXXXcapX=Xget_text(message)
XXXXifXnotXmessage.reply_to_message:
XXXXXXXXawaitXlol.edit("replyXtoXanyXmessageXtoXeditXcaption")
XXXXreplyX=Xmessage.reply_to_message
XXXXtry:
XXXXXXXXawaitXreply.copy(message.chat.id,Xcaption=cap)
XXXXXXXXawaitXlol.delete()
XXXXexceptXRPCErrorXasXi:
XXXXXXXXawaitXlol.edit(i)
XXXXXXXXreturn
