#Copyright(C)2020-2021by@InukaAsith
#ThisprogrammeisapartofInerukiTGbotproject
#
#Thisprogramisfreesoftware:youcanredistributeitand/ormodify
#itunderthetermsoftheGNUAfferoGeneralPublicLicenseaspublishedby
#theFreeSoftwareFoundation,eitherversion3oftheLicense,or
#
#Thisprogramisdistributedinthehopethatitwillbeuseful,
#butWITHOUTANYWARRANTY;withouteventheimpliedwarrantyof
#MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.Seethe
#GNUAfferoGeneralPublicLicenseformoredetails.
#
#YoushouldhavereceivedacopyoftheGNUAfferoGeneralPublicLicense
#alongwiththisprogram.Ifnot,see<https://www.gnu.org/licenses/>.


importlogging
importtime

frompyrogramimportfilters
frompyrogram.errorsimportRPCError
frompyrogram.errors.exceptions.bad_request_400import(
ChannelPrivate,
ChatAdminRequired,
PeerIdInvalid,
UsernameNotOccupied,
UserNotParticipant,
)
frompyrogram.typesimportChatPermissions,InlineKeyboardButton,InlineKeyboardMarkup

fromInerukiimportBOT_ID

#fromInerukiimportOWNER_IDasSUDO_USERS
fromIneruki.services.pyrogramimportpbot
fromIneruki.services.sqlimportforceSubscribe_sqlassql

logging.basicConfig(level=logging.INFO)

static_data_filter=filters.create(
lambda_,__,query:query.data=="onUnMuteRequest"
)


@pbot.on_callback_query(static_data_filter)
def_onUnMuteRequest(client,cb):
try:
user_id=cb.from_user.id
chat_id=cb.message.chat.id
except:
return
chat_db=sql.fs_settings(chat_id)
ifchat_db:
channel=chat_db.channel
try:
chat_member=client.get_chat_member(chat_id,user_id)
except:
return
ifchat_member.restricted_by:
ifchat_member.restricted_by.id==BOT_ID:
try:
client.get_chat_member(channel,user_id)
client.unban_chat_member(chat_id,user_id)
cb.message.delete()
#ifcb.message.reply_to_message.from_user.id==user_id:
#cb.message.delete()
exceptUserNotParticipant:
client.answer_callback_query(
cb.id,
text=f"❗Joinour@{channel}channelandpress'UnMuteMe'button.",
show_alert=True,
)
exceptChannelPrivate:
client.unban_chat_member(chat_id,user_id)
cb.message.delete()

else:
client.answer_callback_query(
cb.id,
text="❗Youhavebeenmutedbyadminsduetosomeotherreason.",
show_alert=True,
)
else:
ifnotclient.get_chat_member(chat_id,BOT_ID).status=="administrator":
client.send_message(
chat_id,
f"❗**{cb.from_user.mention}istryingtoUnMutehimselfbutican'tunmutehimbecauseiamnotanadmininthischataddmeasadminagain.**\n__#Leavingthischat...__",
)

else:
client.answer_callback_query(
cb.id,
text="❗Warning!Don'tpressthebuttonwhenyoucntalk.",
show_alert=True,
)


@pbot.on_message(filters.text&~filters.private&~filters.edited,group=1)
def_check_member(client,message):
chat_id=message.chat.id
chat_db=sql.fs_settings(chat_id)
ifchat_db:
try:
user_id=message.from_user.id
except:
return
try:
if(
notclient.get_chat_member(chat_id,user_id).status
in("administrator","creator")
andnotuser_id==1141839926
):
channel=chat_db.channel
try:
client.get_chat_member(channel,user_id)
exceptUserNotParticipant:
try:
sent_message=message.reply_text(
"Welcome{}🙏\n**Youhaventjoinedour@{}Channelyet**😭\n\nPleaseJoin[OurChannel](https://t.me/{})andhitthe**UNMUTEME**Button.\n\n".format(
message.from_user.mention,channel,channel
),
disable_web_page_preview=True,
reply_markup=InlineKeyboardMarkup(
[
[
InlineKeyboardButton(
"JoinChannel",
url="https://t.me/{}".format(channel),
)
],
[
InlineKeyboardButton(
"UnMuteMe",callback_data="onUnMuteRequest"
)
],
]
),
)
client.restrict_chat_member(
chat_id,user_id,ChatPermissions(can_send_messages=False)
)
exceptChatAdminRequired:
sent_message.edit(
"❗**Inerukiisnotadminhere..**\n__Givemebanpermissionsandretry..\n#EndingFSub...__"
)
exceptRPCError:
return

exceptChatAdminRequired:
client.send_message(
chat_id,
text=f"❗**Inotanadminof@{channel}channel.**\n__Givemeadminofthatchannelandretry.\n#EndingFSub...__",
)
exceptChannelPrivate:
return
except:
return


@pbot.on_message(filters.command(["forcesubscribe","forcesub"])&~filters.private)
defconfig(client,message):
user=client.get_chat_member(message.chat.id,message.from_user.id)
ifuser.statusis"creator"oruser.user.id==1141839926:
chat_id=message.chat.id
iflen(message.command)>1:
input_str=message.command[1]
input_str=input_str.replace("@","")
ifinput_str.lower()in("off","no","disable"):
sql.disapprove(chat_id)
message.reply_text("❌**ForceSubscribeisDisabledSuccessfully.**")
elifinput_str.lower()in("clear"):
sent_message=message.reply_text(
"**Unmutingallmemberswhoaremutedbyme...**"
)
try:
forchat_memberinclient.get_chat_members(
message.chat.id,filter="restricted"
):
ifchat_member.restricted_by.id==BOT_ID:
client.unban_chat_member(chat_id,chat_member.user.id)
time.sleep(1)
sent_message.edit("✅**UnMutedallmemberswhoaremutedbyme.**")
exceptChatAdminRequired:
sent_message.edit(
"❗**Iamnotanadmininthischat.**\n__Ican'tunmutemembersbecauseiamnotanadmininthischatmakemeadminwithbanuserpermission.__"
)
else:
try:
client.get_chat_member(input_str,"me")
sql.add_channel(chat_id,input_str)
message.reply_text(
f"✅**ForceSubscribeisEnabled**\n__ForceSubscribeisenabled,allthegroupmembershavetosubscribethis[channel](https://t.me/{input_str})inordertosendmessagesinthisgroup.__",
disable_web_page_preview=True,
)
exceptUserNotParticipant:
message.reply_text(
f"❗**NotanAdminintheChannel**\n__Iamnotanadmininthe[channel](https://t.me/{input_str}).AddmeasaadmininordertoenableForceSubscribe.__",
disable_web_page_preview=True,
)
except(UsernameNotOccupied,PeerIdInvalid):
message.reply_text(f"❗**InvalidChannelUsername.**")
exceptExceptionaserr:
message.reply_text(f"❗**ERROR:**```{err}```")
else:
ifsql.fs_settings(chat_id):
message.reply_text(
f"✅**ForceSubscribeisenabledinthischat.**\n__Forthis[Channel](https://t.me/{sql.fs_settings(chat_id).channel})__",
disable_web_page_preview=True,
)
else:
message.reply_text("❌**ForceSubscribeisdisabledinthischat.**")
else:
message.reply_text(
"❗**GroupCreatorRequired**\n__Youhavetobethegroupcreatortodothat.__"
)


__help__="""
<b>ForceSubscribe:</b>
-Inerukicanmutememberswhoarenotsubscribedyourchanneluntiltheysubscribe
-WhenenabledIwillmuteunsubscribedmembersandshowthemaunmutebutton.WhentheypressedthebuttonIwillunmutethem
<b>Setup</b>
1)Firstofalladdmeinthegroupasadminwithbanuserspermissionandinthechannelasadmin.
Note:Onlycreatorofthegroupcansetupmeandiwillnotallowforcesubscribeagainifnotdoneso.

<b>Commmands</b>
-/forcesubscribe-Togetthecurrentsettings.
-/forcesubscribeno/off/disable-ToturnofForceSubscribe.
-/forcesubscribe{channelusername}-Toturnonandsetupthechannel.
-/forcesubscribeclear-Tounmuteallmemberswhomutedbyme.
Note:/forcesubisanaliasof/forcesubscribe

"""
__mod_name__="ForceSubscribe"
