#XXXXCopyrightX(C)X2020-2021XbyX@InukaAsith
#XXXXThisXprogrammeXisXaXpartXofXInerukiXTGXbotXproject
#
#XXXXThisXprogramXisXfreeXsoftware:XyouXcanXredistributeXitXand/orXmodify
#XXXXitXunderXtheXtermsXofXtheXGNUXAfferoXGeneralXPublicXLicenseXasXpublishedXby
#XXXXtheXFreeXSoftwareXFoundation,XeitherXversionX3XofXtheXLicense,Xor
#
#XXXXThisXprogramXisXdistributedXinXtheXhopeXthatXitXwillXbeXuseful,
#XXXXbutXWITHOUTXANYXWARRANTY;XwithoutXevenXtheXimpliedXwarrantyXof
#XXXXMERCHANTABILITYXorXFITNESSXFORXAXPARTICULARXPURPOSE.XXSeeXthe
#XXXXGNUXAfferoXGeneralXPublicXLicenseXforXmoreXdetails.
#
#XXXXYouXshouldXhaveXreceivedXaXcopyXofXtheXGNUXAfferoXGeneralXPublicXLicense
#XXXXalongXwithXthisXprogram.XXIfXnot,XseeX<https://www.gnu.org/licenses/>.


importXlogging
importXtime

fromXpyrogramXimportXfilters
fromXpyrogram.errorsXimportXRPCError
fromXpyrogram.errors.exceptions.bad_request_400XimportX(
XXXXChannelPrivate,
XXXXChatAdminRequired,
XXXXPeerIdInvalid,
XXXXUsernameNotOccupied,
XXXXUserNotParticipant,
)
fromXpyrogram.typesXimportXChatPermissions,XInlineKeyboardButton,XInlineKeyboardMarkup

fromXInerukiXXimportXBOT_ID

#XfromXInerukiXXimportXOWNER_IDXasXSUDO_USERS
fromXInerukiX.services.pyrogramXimportXpbot
fromXInerukiX.services.sqlXimportXforceSubscribe_sqlXasXsql

logging.basicConfig(level=logging.INFO)

static_data_filterX=Xfilters.create(
XXXXlambdaX_,X__,Xquery:Xquery.dataX==X"onUnMuteRequest"
)


@pbot.on_callback_query(static_data_filter)
defX_onUnMuteRequest(client,Xcb):
XXXXtry:
XXXXXXXXuser_idX=Xcb.from_user.id
XXXXXXXXchat_idX=Xcb.message.chat.id
XXXXexcept:
XXXXXXXXreturn
XXXXchat_dbX=Xsql.fs_settings(chat_id)
XXXXifXchat_db:
XXXXXXXXchannelX=Xchat_db.channel
XXXXXXXXtry:
XXXXXXXXXXXXchat_memberX=Xclient.get_chat_member(chat_id,Xuser_id)
XXXXXXXXexcept:
XXXXXXXXXXXXreturn
XXXXXXXXifXchat_member.restricted_by:
XXXXXXXXXXXXifXchat_member.restricted_by.idX==XBOT_ID:
XXXXXXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXXXXXclient.get_chat_member(channel,Xuser_id)
XXXXXXXXXXXXXXXXXXXXclient.unban_chat_member(chat_id,Xuser_id)
XXXXXXXXXXXXXXXXXXXXcb.message.delete()
XXXXXXXXXXXXXXXXXXXX#XifXcb.message.reply_to_message.from_user.idX==Xuser_id:
XXXXXXXXXXXXXXXXXXXX#Xcb.message.delete()
XXXXXXXXXXXXXXXXexceptXUserNotParticipant:
XXXXXXXXXXXXXXXXXXXXclient.answer_callback_query(
XXXXXXXXXXXXXXXXXXXXXXXXcb.id,
XXXXXXXXXXXXXXXXXXXXXXXXtext=f"❗XJoinXourX@{channel}XchannelXandXpressX'UnMuteXMe'Xbutton.",
XXXXXXXXXXXXXXXXXXXXXXXXshow_alert=True,
XXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXexceptXChannelPrivate:
XXXXXXXXXXXXXXXXXXXXclient.unban_chat_member(chat_id,Xuser_id)
XXXXXXXXXXXXXXXXXXXXcb.message.delete()

XXXXXXXXXXXXelse:
XXXXXXXXXXXXXXXXclient.answer_callback_query(
XXXXXXXXXXXXXXXXXXXXcb.id,
XXXXXXXXXXXXXXXXXXXXtext="❗XYouXhaveXbeenXmutedXbyXadminsXdueXtoXsomeXotherXreason.",
XXXXXXXXXXXXXXXXXXXXshow_alert=True,
XXXXXXXXXXXXXXXX)
XXXXXXXXelse:
XXXXXXXXXXXXifXnotXclient.get_chat_member(chat_id,XBOT_ID).statusX==X"administrator":
XXXXXXXXXXXXXXXXclient.send_message(
XXXXXXXXXXXXXXXXXXXXchat_id,
XXXXXXXXXXXXXXXXXXXXf"❗X**{cb.from_user.mention}XisXtryingXtoXUnMuteXhimselfXbutXiXcan'tXunmuteXhimXbecauseXiXamXnotXanXadminXinXthisXchatXaddXmeXasXadminXagain.**\n__#LeavingXthisXchat...__",
XXXXXXXXXXXXXXXX)

XXXXXXXXXXXXelse:
XXXXXXXXXXXXXXXXclient.answer_callback_query(
XXXXXXXXXXXXXXXXXXXXcb.id,
XXXXXXXXXXXXXXXXXXXXtext="❗XWarning!XDon'tXpressXtheXbuttonXwhenXyouXcnXtalk.",
XXXXXXXXXXXXXXXXXXXXshow_alert=True,
XXXXXXXXXXXXXXXX)


@pbot.on_message(filters.textX&X~filters.privateX&X~filters.edited,Xgroup=1)
defX_check_member(client,Xmessage):
XXXXchat_idX=Xmessage.chat.id
XXXXchat_dbX=Xsql.fs_settings(chat_id)
XXXXifXchat_db:
XXXXXXXXtry:
XXXXXXXXXXXXuser_idX=Xmessage.from_user.id
XXXXXXXXexcept:
XXXXXXXXXXXXreturn
XXXXXXXXtry:
XXXXXXXXXXXXifX(
XXXXXXXXXXXXXXXXnotXclient.get_chat_member(chat_id,Xuser_id).status
XXXXXXXXXXXXXXXXinX("administrator",X"creator")
XXXXXXXXXXXXXXXXandXnotXuser_idX==X1141839926
XXXXXXXXXXXX):
XXXXXXXXXXXXXXXXchannelX=Xchat_db.channel
XXXXXXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXXXXXclient.get_chat_member(channel,Xuser_id)
XXXXXXXXXXXXXXXXexceptXUserNotParticipant:
XXXXXXXXXXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXXXXXXXXXsent_messageX=Xmessage.reply_text(
XXXXXXXXXXXXXXXXXXXXXXXXXXXX"WelcomeX{}X🙏X\nX**YouXhaventXjoinedXourX@{}XChannelXyet**X😭X\nX\nPleaseXJoinX[OurXChannel](https://t.me/{})XandXhitXtheX**UNMUTEXME**XButton.X\nX\nX".format(
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXmessage.from_user.mention,Xchannel,Xchannel
XXXXXXXXXXXXXXXXXXXXXXXXXXXX),
XXXXXXXXXXXXXXXXXXXXXXXXXXXXdisable_web_page_preview=True,
XXXXXXXXXXXXXXXXXXXXXXXXXXXXreply_markup=InlineKeyboardMarkup(
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXInlineKeyboardButton(
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"JoinXChannel",
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXurl="https://t.me/{}".format(channel),
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX],
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX[
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXInlineKeyboardButton(
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"UnMuteXMe",Xcallback_data="onUnMuteRequest"
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX],
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
XXXXXXXXXXXXXXXXXXXXXXXXXXXX),
XXXXXXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXXXXXXXXXclient.restrict_chat_member(
XXXXXXXXXXXXXXXXXXXXXXXXXXXXchat_id,Xuser_id,XChatPermissions(can_send_messages=False)
XXXXXXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXXXXXexceptXChatAdminRequired:
XXXXXXXXXXXXXXXXXXXXXXXXsent_message.edit(
XXXXXXXXXXXXXXXXXXXXXXXXXXXX"❗X**InerukiXisXnotXadminXhere..**\n__GiveXmeXbanXpermissionsXandXretry..X\n#EndingXFSub...__"
XXXXXXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXXXXXexceptXRPCError:
XXXXXXXXXXXXXXXXXXXXXXXXreturn

XXXXXXXXXXXXXXXXexceptXChatAdminRequired:
XXXXXXXXXXXXXXXXXXXXclient.send_message(
XXXXXXXXXXXXXXXXXXXXXXXXchat_id,
XXXXXXXXXXXXXXXXXXXXXXXXtext=f"❗X**IXnotXanXadminXofX@{channel}Xchannel.**\n__GiveXmeXadminXofXthatXchannelXandXretry.\n#EndingXFSub...__",
XXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXexceptXChannelPrivate:
XXXXXXXXXXXXXXXXXXXXreturn
XXXXXXXXexcept:
XXXXXXXXXXXXreturn


@pbot.on_message(filters.command(["forcesubscribe",X"forcesub"])X&X~filters.private)
defXconfig(client,Xmessage):
XXXXuserX=Xclient.get_chat_member(message.chat.id,Xmessage.from_user.id)
XXXXifXuser.statusXisX"creator"XorXuser.user.idX==X1141839926:
XXXXXXXXchat_idX=Xmessage.chat.id
XXXXXXXXifXlen(message.command)X>X1:
XXXXXXXXXXXXinput_strX=Xmessage.command[1]
XXXXXXXXXXXXinput_strX=Xinput_str.replace("@",X"")
XXXXXXXXXXXXifXinput_str.lower()XinX("off",X"no",X"disable"):
XXXXXXXXXXXXXXXXsql.disapprove(chat_id)
XXXXXXXXXXXXXXXXmessage.reply_text("❌X**ForceXSubscribeXisXDisabledXSuccessfully.**")
XXXXXXXXXXXXelifXinput_str.lower()XinX("clear"):
XXXXXXXXXXXXXXXXsent_messageX=Xmessage.reply_text(
XXXXXXXXXXXXXXXXXXXX"**UnmutingXallXmembersXwhoXareXmutedXbyXme...**"
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXXXXXforXchat_memberXinXclient.get_chat_members(
XXXXXXXXXXXXXXXXXXXXXXXXmessage.chat.id,Xfilter="restricted"
XXXXXXXXXXXXXXXXXXXX):
XXXXXXXXXXXXXXXXXXXXXXXXifXchat_member.restricted_by.idX==XBOT_ID:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXclient.unban_chat_member(chat_id,Xchat_member.user.id)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXtime.sleep(1)
XXXXXXXXXXXXXXXXXXXXsent_message.edit("✅X**UnMutedXallXmembersXwhoXareXmutedXbyXme.**")
XXXXXXXXXXXXXXXXexceptXChatAdminRequired:
XXXXXXXXXXXXXXXXXXXXsent_message.edit(
XXXXXXXXXXXXXXXXXXXXXXXX"❗X**IXamXnotXanXadminXinXthisXchat.**\n__IXcan'tXunmuteXmembersXbecauseXiXamXnotXanXadminXinXthisXchatXmakeXmeXadminXwithXbanXuserXpermission.__"
XXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXelse:
XXXXXXXXXXXXXXXXtry:
XXXXXXXXXXXXXXXXXXXXclient.get_chat_member(input_str,X"me")
XXXXXXXXXXXXXXXXXXXXsql.add_channel(chat_id,Xinput_str)
XXXXXXXXXXXXXXXXXXXXmessage.reply_text(
XXXXXXXXXXXXXXXXXXXXXXXXf"✅X**ForceXSubscribeXisXEnabled**\n__ForceXSubscribeXisXenabled,XallXtheXgroupXmembersXhaveXtoXsubscribeXthisX[channel](https://t.me/{input_str})XinXorderXtoXsendXmessagesXinXthisXgroup.__",
XXXXXXXXXXXXXXXXXXXXXXXXdisable_web_page_preview=True,
XXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXexceptXUserNotParticipant:
XXXXXXXXXXXXXXXXXXXXmessage.reply_text(
XXXXXXXXXXXXXXXXXXXXXXXXf"❗X**NotXanXAdminXinXtheXChannel**\n__IXamXnotXanXadminXinXtheX[channel](https://t.me/{input_str}).XAddXmeXasXaXadminXinXorderXtoXenableXForceSubscribe.__",
XXXXXXXXXXXXXXXXXXXXXXXXdisable_web_page_preview=True,
XXXXXXXXXXXXXXXXXXXX)
XXXXXXXXXXXXXXXXexceptX(UsernameNotOccupied,XPeerIdInvalid):
XXXXXXXXXXXXXXXXXXXXmessage.reply_text(f"❗X**InvalidXChannelXUsername.**")
XXXXXXXXXXXXXXXXexceptXExceptionXasXerr:
XXXXXXXXXXXXXXXXXXXXmessage.reply_text(f"❗X**ERROR:**X```{err}```")
XXXXXXXXelse:
XXXXXXXXXXXXifXsql.fs_settings(chat_id):
XXXXXXXXXXXXXXXXmessage.reply_text(
XXXXXXXXXXXXXXXXXXXXf"✅X**ForceXSubscribeXisXenabledXinXthisXchat.**\n__ForXthisX[Channel](https://t.me/{sql.fs_settings(chat_id).channel})__",
XXXXXXXXXXXXXXXXXXXXdisable_web_page_preview=True,
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXXelse:
XXXXXXXXXXXXXXXXmessage.reply_text("❌X**ForceXSubscribeXisXdisabledXinXthisXchat.**")
XXXXelse:
XXXXXXXXmessage.reply_text(
XXXXXXXXXXXX"❗X**GroupXCreatorXRequired**\n__YouXhaveXtoXbeXtheXgroupXcreatorXtoXdoXthat.__"
XXXXXXXX)


__help__X=X"""
<b>ForceSubscribe:</b>
-XInerukiXcanXmuteXmembersXwhoXareXnotXsubscribedXyourXchannelXuntilXtheyXsubscribe
-XWhenXenabledXIXwillXmuteXunsubscribedXmembersXandXshowXthemXaXunmuteXbutton.XWhenXtheyXpressedXtheXbuttonXIXwillXunmuteXthem
<b>Setup</b>
1)XFirstXofXallXaddXmeXinXtheXgroupXasXadminXwithXbanXusersXpermissionXandXinXtheXchannelXasXadmin.
Note:XOnlyXcreatorXofXtheXgroupXcanXsetupXmeXandXiXwillXnotXallowXforceXsubscribeXagainXifXnotXdoneXso.
X
<b>Commmands</b>
X-X/forcesubscribeX-XToXgetXtheXcurrentXsettings.
X-X/forcesubscribeXno/off/disableX-XToXturnXofXForceSubscribe.
X-X/forcesubscribeX{channelXusername}X-XToXturnXonXandXsetupXtheXchannel.
X-X/forcesubscribeXclearX-XToXunmuteXallXmembersXwhoXmutedXbyXme.
Note:X/forcesubXisXanXaliasXofX/forcesubscribe
X
"""
__mod_name__X=X"ForceXSubscribeX"
