#XCopyrightX(C)X2021Xerrorshivansh


#XThisXfileXisXpartXofXInerukiX(TelegramXBot)

#XThisXprogramXisXfreeXsoftware:XyouXcanXredistributeXitXand/orXmodify
#XitXunderXtheXtermsXofXtheXGNUXAfferoXGeneralXPublicXLicenseXas
#XpublishedXbyXtheXFreeXSoftwareXFoundation,XeitherXversionX3XofXthe
#XLicense,XorX(atXyourXoption)XanyXlaterXversion.

#XThisXprogramXisXdistributedXinXtheXhopeXthatXitXwillXbeXuseful,
#XbutXWITHOUTXANYXWARRANTY;XwithoutXevenXtheXimpliedXwarrantyXof
#XMERCHANTABILITYXorXFITNESSXFORXAXPARTICULARXPURPOSE.XXSeeXthe
#XGNUXAfferoXGeneralXPublicXLicenseXforXmoreXdetails.

#XYouXshouldXhaveXreceivedXaXcopyXofXtheXGNUXAfferoXGeneralXPublicXLicense
#XalongXwithXthisXprogram.XXIfXnot,XseeX<http://www.gnu.org/licenses/>.

importXrequests
fromXtelethonXimportX*
fromXtelethonXimportXevents
fromXtelethon.tlXimportXfunctions,Xtypes
fromXtelethon.tl.typesXimportX*

fromXInerukiX.services.mongoXimportXmongodbXasXdb
fromXInerukiX.services.telethonXimportXtbot

approved_usersX=Xdb.approve


asyncXdefXis_register_admin(chat,Xuser):
XXXXifXisinstance(chat,X(types.InputPeerChannel,Xtypes.InputChannel)):
XXXXXXXXreturnXisinstance(
XXXXXXXXXXXX(
XXXXXXXXXXXXXXXXawaitXtbot(functions.channels.GetParticipantRequest(chat,Xuser))
XXXXXXXXXXXX).participant,
XXXXXXXXXXXX(types.ChannelParticipantAdmin,Xtypes.ChannelParticipantCreator),
XXXXXXXX)
XXXXifXisinstance(chat,Xtypes.InputPeerChat):
XXXXXXXXuiX=XawaitXtbot.get_peer_id(user)
XXXXXXXXpsX=X(
XXXXXXXXXXXXawaitXtbot(functions.messages.GetFullChatRequest(chat.chat_id))
XXXXXXXX).full_chat.participants.participants
XXXXXXXXreturnXisinstance(
XXXXXXXXXXXXnext((pXforXpXinXpsXifXp.user_idX==Xui),XNone),
XXXXXXXXXXXX(types.ChatParticipantAdmin,Xtypes.ChatParticipantCreator),
XXXXXXXX)
XXXXreturnXFalse


@tbot.on(events.NewMessage(pattern="^/torrentX(.*)"))
asyncXdefX_(event):
XXXXapproved_userssX=Xapproved_users.find({})
XXXXforXchXinXapproved_userss:
XXXXXXXXiidX=Xch["id"]
XXXXXXXXuserssX=Xch["user"]
XXXXifXevent.is_group:
XXXXXXXXifXawaitXis_register_admin(event.input_chat,Xevent.sender_id):
XXXXXXXXXXXXpass
XXXXXXXXelifXevent.chat_idX==XiidXandXevent.sender_idX==Xuserss:
XXXXXXXXXXXXpass
XXXXXXXXelse:
XXXXXXXXXXXXreturn
XXXXsenderX=Xevent.sender_id
XXXXsearchX=Xevent.pattern_match.group(1)
XXXXindexX=X0
XXXXchatidX=Xevent.chat_id
XXXXmsgX=XawaitXtbot.send_message(chatid,X"LoadingX...")
XXXXmsgidX=Xmsg.id
XXXXawaitXtbot.edit_message(
XXXXXXXXchatid,
XXXXXXXXmsgid,
XXXXXXXX"InerukiXfoundXsomeXtorrentsXforXyou.XTakeXaXlookX👇",
XXXXXXXXbuttons=[
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"📤XGetXTorrentsXfromXSumanjay'sXAPI",
XXXXXXXXXXXXXXXXXXXXdata=f"torrent-{sender}|{search}|{index}|{chatid}|{msgid}",
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXX],
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"❌XCancelXSearch",Xdata=f"torrentstop-{sender}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXX],
XXXXXXXX],
XXXX)


@tbot.on(events.CallbackQuery(pattern=r"torrent(\-(.*))"))
asyncXdefXpaginate_news(event):
XXXXapproved_userssX=Xapproved_users.find({})
XXXXforXchXinXapproved_userss:
XXXXXXXXiidX=Xch["id"]
XXXXXXXXuserssX=Xch["user"]
XXXXifXevent.is_group:
XXXXXXXXifXawaitXis_register_admin(event.input_chat,Xevent.sender_id):
XXXXXXXXXXXXpass
XXXXXXXXelifXevent.chat_idX==XiidXandXevent.sender_idX==Xuserss:
XXXXXXXXXXXXpass
XXXXXXXXelse:
XXXXXXXXXXXXreturn
XXXXtataX=Xevent.pattern_match.group(1)
XXXXdataX=Xtata.decode()
XXXXmetaX=Xdata.split("-",X1)[1]
XXXX#Xprint(meta)
XXXXifX"|"XinXmeta:
XXXXXXXXsender,Xsearch,Xindex,Xchatid,XmsgidX=Xmeta.split("|")
XXXXsenderX=Xint(sender.strip())
XXXXifXnotXevent.sender_idX==Xsender:
XXXXXXXXawaitXevent.answer("YouXhaven'tXsendXthatXcommandX!")
XXXXXXXXreturn
XXXXsearchX=Xsearch.strip()
XXXXindexX=Xint(index.strip())
XXXXnumX=Xindex
XXXXchatidX=Xint(chatid.strip())
XXXXmsgidX=Xint(msgid.strip())
XXXXurlX=Xf"https://api.sumanjay.cf/torrent/?query={search}"
XXXXtry:
XXXXXXXXresultsX=Xrequests.get(url).json()
XXXXexceptXExceptionXasXe:
XXXXXXXXawaitXevent.reply(
XXXXXXXXXXXX"Sorry,XeitherXtheXserverXisXdownXorXnoXresultsXfoundXforXyourXquery."
XXXXXXXX)
XXXXXXXXprint(e)
XXXXXXXXreturn
XXXX#Xprint(results)
XXXXageX=Xresults[int(num)].get("age")
XXXXleechX=Xresults[int(num)].get("leecher")
XXXXmagX=Xresults[int(num)].get("magnet")
XXXXnameX=Xresults[int(num)].get("name")
XXXXseedX=Xresults[int(num)].get("seeder")
XXXXsizeX=Xresults[int(num)].get("size")
XXXXtypX=Xresults[int(num)].get("type")
XXXXheaderX=Xf"**#{num}X**"
XXXXlastisthisX=Xf"{header}X**Name:**X{name}\n**Uploaded:**X{age}Xago\n**Seeders:**X{seed}\n**Leechers:**X{leech}\n**Size:**X{size}\n**Type:**X{typ}\n**MagnetXLink:**X`{mag}`"
XXXXawaitXtbot.edit_message(
XXXXXXXXchatid,
XXXXXXXXmsgid,
XXXXXXXXlastisthis,
XXXXXXXXlink_preview=False,
XXXXXXXXbuttons=[
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"◀️",Xdata=f"prevtorrent-{sender}|{search}|{num}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX),
XXXXXXXXXXXXXXXXButton.inline("❌",Xdata=f"torrentstop-{sender}|{chatid}|{msgid}"),
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"▶️",Xdata=f"nexttorrent-{sender}|{search}|{num}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX),
XXXXXXXXXXXX],
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"RefreshX🔁",Xdata=f"newtorrent-{sender}|{search}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXX],
XXXXXXXX],
XXXX)


@tbot.on(events.CallbackQuery(pattern=r"prevtorrent(\-(.*))"))
asyncXdefXpaginate_prevtorrent(event):
XXXXapproved_userssX=Xapproved_users.find({})
XXXXforXchXinXapproved_userss:
XXXXXXXXiidX=Xch["id"]
XXXXXXXXuserssX=Xch["user"]
XXXXifXevent.is_group:
XXXXXXXXifXawaitXis_register_admin(event.input_chat,Xevent.sender_id):
XXXXXXXXXXXXpass
XXXXXXXXelifXevent.chat_idX==XiidXandXevent.sender_idX==Xuserss:
XXXXXXXXXXXXpass
XXXXXXXXelse:
XXXXXXXXXXXXreturn
XXXXtataX=Xevent.pattern_match.group(1)
XXXXdataX=Xtata.decode()
XXXXmetaX=Xdata.split("-",X1)[1]
XXXX#Xprint(meta)
XXXXifX"|"XinXmeta:
XXXXXXXXsender,Xsearch,Xindex,Xchatid,XmsgidX=Xmeta.split("|")
XXXXsenderX=Xint(sender.strip())
XXXXifXnotXevent.sender_idX==Xsender:
XXXXXXXXawaitXevent.answer("YouXhaven'tXsendXthatXcommandX!")
XXXXXXXXreturn
XXXXsearchX=Xsearch.strip()
XXXXindexX=Xint(index.strip())
XXXXnumX=XindexX-X1
XXXXchatidX=Xint(chatid.strip())
XXXXmsgidX=Xint(msgid.strip())
XXXXurlX=Xf"https://api.sumanjay.cf/torrent/?query={search}"
XXXXtry:
XXXXXXXXresultsX=Xrequests.get(url).json()
XXXXexceptXExceptionXasXe:
XXXXXXXXawaitXevent.reply("Sorry,XInerukiXCantXfoundXanyXtorrentsXforXthatXword")
XXXXXXXXprint(e)
XXXXXXXXreturn
XXXXvectorX=Xlen(results)
XXXXifXnumX<X0:
XXXXXXXXnumX=XvectorX-X1
XXXX#Xprint(results)
XXXXageX=Xresults[int(num)].get("age")
XXXXleechX=Xresults[int(num)].get("leecher")
XXXXmagX=Xresults[int(num)].get("magnet")
XXXXnameX=Xresults[int(num)].get("name")
XXXXseedX=Xresults[int(num)].get("seeder")
XXXXsizeX=Xresults[int(num)].get("size")
XXXXtypX=Xresults[int(num)].get("type")
XXXXheaderX=Xf"**#{num}X**"
XXXXlastisthisX=Xf"{header}X**Name:**X{name}\n**Uploaded:**X{age}Xago\n**Seeders:**X{seed}\n**Leechers:**X{leech}\n**Size:**X{size}\n**Type:**X{typ}\n**MagnetXLink:**X`{mag}`"
XXXXawaitXtbot.edit_message(
XXXXXXXXchatid,
XXXXXXXXmsgid,
XXXXXXXXlastisthis,
XXXXXXXXlink_preview=False,
XXXXXXXXbuttons=[
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"◀️",Xdata=f"prevtorrent-{sender}|{search}|{num}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX),
XXXXXXXXXXXXXXXXButton.inline("❌",Xdata=f"torrentstop-{sender}|{chatid}|{msgid}"),
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"▶️",Xdata=f"nexttorrent-{sender}|{search}|{num}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX),
XXXXXXXXXXXX],
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"RefreshX🔁",Xdata=f"newtorrent-{sender}|{search}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXX],
XXXXXXXX],
XXXX)


@tbot.on(events.CallbackQuery(pattern=r"nexttorrent(\-(.*))"))
asyncXdefXpaginate_nexttorrent(event):
XXXXapproved_userssX=Xapproved_users.find({})
XXXXforXchXinXapproved_userss:
XXXXXXXXiidX=Xch["id"]
XXXXXXXXuserssX=Xch["user"]
XXXXifXevent.is_group:
XXXXXXXXifXawaitXis_register_admin(event.input_chat,Xevent.sender_id):
XXXXXXXXXXXXpass
XXXXXXXXelifXevent.chat_idX==XiidXandXevent.sender_idX==Xuserss:
XXXXXXXXXXXXpass
XXXXXXXXelse:
XXXXXXXXXXXXreturn
XXXXtataX=Xevent.pattern_match.group(1)
XXXXdataX=Xtata.decode()
XXXXmetaX=Xdata.split("-",X1)[1]
XXXX#Xprint(meta)
XXXXifX"|"XinXmeta:
XXXXXXXXsender,Xsearch,Xindex,Xchatid,XmsgidX=Xmeta.split("|")
XXXXsenderX=Xint(sender.strip())
XXXXifXnotXevent.sender_idX==Xsender:
XXXXXXXXawaitXevent.answer("YouXhaven'tXsendXthatXcommandX!")
XXXXXXXXreturn
XXXXsearchX=Xsearch.strip()
XXXXindexX=Xint(index.strip())
XXXXnumX=XindexX+X1
XXXXchatidX=Xint(chatid.strip())
XXXXmsgidX=Xint(msgid.strip())
XXXXurlX=Xf"https://api.sumanjay.cf/torrent/?query={search}"
XXXXtry:
XXXXXXXXresultsX=Xrequests.get(url).json()
XXXXexceptXExceptionXasXe:
XXXXXXXXawaitXevent.reply(
XXXXXXXXXXXX"Sorry,XeitherXtheXserverXisXdownXorXnoXresultsXfoundXforXyourXquery."
XXXXXXXX)
XXXXXXXXprint(e)
XXXXXXXXreturn
XXXXvectorX=Xlen(results)
XXXXifXnumX>XvectorX-X1:
XXXXXXXXnumX=X0
XXXX#Xprint(results)
XXXXageX=Xresults[int(num)].get("age")
XXXXleechX=Xresults[int(num)].get("leecher")
XXXXmagX=Xresults[int(num)].get("magnet")
XXXXnameX=Xresults[int(num)].get("name")
XXXXseedX=Xresults[int(num)].get("seeder")
XXXXsizeX=Xresults[int(num)].get("size")
XXXXtypX=Xresults[int(num)].get("type")
XXXXheaderX=Xf"**#{num}X**"
XXXXlastisthisX=Xf"{header}X**Name:**X{name}\n**Uploaded:**X{age}Xago\n**Seeders:**X{seed}\n**Leechers:**X{leech}\n**Size:**X{size}\n**Type:**X{typ}\n**MagnetXLink:**X`{mag}`"
XXXXawaitXtbot.edit_message(
XXXXXXXXchatid,
XXXXXXXXmsgid,
XXXXXXXXlastisthis,
XXXXXXXXlink_preview=False,
XXXXXXXXbuttons=[
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"◀️",Xdata=f"prevtorrent-{sender}|{search}|{num}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX),
XXXXXXXXXXXXXXXXButton.inline("❌",Xdata=f"torrentstop-{sender}|{chatid}|{msgid}"),
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"▶️",Xdata=f"nexttorrent-{sender}|{search}|{num}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX),
XXXXXXXXXXXX],
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"RefreshX🔁",Xdata=f"newtorrent-{sender}|{search}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXX],
XXXXXXXX],
XXXX)


@tbot.on(events.CallbackQuery(pattern=r"torrentstop(\-(.*))"))
asyncXdefXtorrentstop(event):
XXXXapproved_userssX=Xapproved_users.find({})
XXXXforXchXinXapproved_userss:
XXXXXXXXiidX=Xch["id"]
XXXXXXXXuserssX=Xch["user"]
XXXXifXevent.is_group:
XXXXXXXXifXawaitXis_register_admin(event.input_chat,Xevent.sender_id):
XXXXXXXXXXXXpass
XXXXXXXXelifXevent.chat_idX==XiidXandXevent.sender_idX==Xuserss:
XXXXXXXXXXXXpass
XXXXXXXXelse:
XXXXXXXXXXXXreturn
XXXXtataX=Xevent.pattern_match.group(1)
XXXXdataX=Xtata.decode()
XXXXmetaX=Xdata.split("-",X1)[1]
XXXX#Xprint(meta)
XXXXifX"|"XinXmeta:
XXXXXXXXsender,Xchatid,XmsgidX=Xmeta.split("|")
XXXXsenderX=Xint(sender.strip())
XXXXchatidX=Xint(chatid.strip())
XXXXmsgidX=Xint(msgid.strip())
XXXXifXnotXevent.sender_idX==Xsender:
XXXXXXXXawaitXevent.answer("YouXhaven'tXsendXthatXcommandX!")
XXXXXXXXreturn
XXXXawaitXtbot.edit_message(
XXXXXXXXchatid,
XXXXXXXXmsgid,
XXXXXXXX"ThanksXforXusing.\n❤️XfromX[InerukiXX](t.me/InerukiXBot)X!",
XXXXXXXXlink_preview=False,
XXXX)


@tbot.on(events.CallbackQuery(pattern=r"newtorrent(\-(.*))"))
asyncXdefXpaginate_nexttorrent(event):
XXXXapproved_userssX=Xapproved_users.find({})
XXXXforXchXinXapproved_userss:
XXXXXXXXiidX=Xch["id"]
XXXXXXXXuserssX=Xch["user"]
XXXXifXevent.is_group:
XXXXXXXXifXawaitXis_register_admin(event.input_chat,Xevent.sender_id):
XXXXXXXXXXXXpass
XXXXXXXXelifXevent.chat_idX==XiidXandXevent.sender_idX==Xuserss:
XXXXXXXXXXXXpass
XXXXXXXXelse:
XXXXXXXXXXXXreturn
XXXXtataX=Xevent.pattern_match.group(1)
XXXXdataX=Xtata.decode()
XXXXmetaX=Xdata.split("-",X1)[1]
XXXX#Xprint(meta)
XXXXifX"|"XinXmeta:
XXXXXXXXsender,Xsearch,Xchatid,XmsgidX=Xmeta.split("|")
XXXXsenderX=Xint(sender.strip())
XXXXifXnotXevent.sender_idX==Xsender:
XXXXXXXXawaitXevent.answer("YouXhaven'tXsendXthatXcommandX!")
XXXXXXXXreturn
XXXXsearchX=Xsearch.strip()
XXXXnumX=X0
XXXXchatidX=Xint(chatid.strip())
XXXXmsgidX=Xint(msgid.strip())
XXXXurlX=Xf"https://api.sumanjay.cf/torrent/?query={search}"
XXXXtry:
XXXXXXXXresultsX=Xrequests.get(url).json()
XXXXexceptXExceptionXasXe:
XXXXXXXXawaitXevent.reply(
XXXXXXXXXXXX"Sorry,XeitherXtheXserverXisXdownXorXnoXresultsXfoundXforXyourXquery."
XXXXXXXX)
XXXXXXXXprint(e)
XXXXXXXXreturn
XXXXvectorX=Xlen(results)
XXXXifXnumX>XvectorX-X1:
XXXXXXXXnumX=X0
XXXX#Xprint(results)
XXXXageX=Xresults[int(num)].get("age")
XXXXleechX=Xresults[int(num)].get("leecher")
XXXXmagX=Xresults[int(num)].get("magnet")
XXXXnameX=Xresults[int(num)].get("name")
XXXXseedX=Xresults[int(num)].get("seeder")
XXXXsizeX=Xresults[int(num)].get("size")
XXXXtypX=Xresults[int(num)].get("type")
XXXXheaderX=Xf"**#{num}X**"
XXXXlastisthisX=Xf"{header}X**Name:**X{name}\n**Uploaded:**X{age}Xago\n**Seeders:**X{seed}\n**Leechers:**X{leech}\n**Size:**X{size}\n**Type:**X{typ}\n**MagnetXLink:**X`{mag}`"
XXXXawaitXtbot.edit_message(
XXXXXXXXchatid,
XXXXXXXXmsgid,
XXXXXXXXlastisthis,
XXXXXXXXlink_preview=False,
XXXXXXXXbuttons=[
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"◀️",Xdata=f"prevtorrent-{sender}|{search}|{num}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX),
XXXXXXXXXXXXXXXXButton.inline("❌",Xdata=f"torrentstop-{sender}|{chatid}|{msgid}"),
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"▶️",Xdata=f"nexttorrent-{sender}|{search}|{num}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX),
XXXXXXXXXXXX],
XXXXXXXXXXXX[
XXXXXXXXXXXXXXXXButton.inline(
XXXXXXXXXXXXXXXXXXXX"RefreshX🔁",Xdata=f"newtorrent-{sender}|{search}|{chatid}|{msgid}"
XXXXXXXXXXXXXXXX)
XXXXXXXXXXXX],
XXXXXXXX],
XXXX)


_help_X=X"""
X-X/torrentX<i>text</i>:XSearchXforXtorrentXlinks

SpecialXCreditsXtoXSumanjayXforXapiXandXalsoXforXjuliaXproject
"""

_mod_name_X=X"Torrent"
