name: Change

on:
  push:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "X"

          replace: " "

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Change it'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: errorshivansh

          commit_user_email: shivanshraghuvanshi2005@gmail.com
